name: Run web scrapper

on: [workflow_dispatch]
# If scraping should be scheduled:
# - [workflow_dispatch]
#  schedule:
#    -cron:  '0 0 1 * *'
#  At 12:00 AM, on day 1 of the month
#  https://crontab.cronhub.io/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Script
        run: python main.py

      - name: Commit Python changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update posts
        id: auto-commit-action
