name: Run web scrapper

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Script
        run: python main.py

      - name: Commit Python changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update posts
        id: auto-commit-action

      # Jekyll build step
      - name: Build Jekyll site
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build

      # Switch to the `new-gh-pages` branch and move files
      - name: Switch to new-gh-pages branch and commit changes
        run: |
          git checkout new-gh-pages
          git rm -rf .
          git add _site/
          git mv _site/* .
          git rm -r _site/

      # Commit the changes to the new-gh-pages branch
      - name: Commit Changes to new-gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update gh-pages with new site
        id: auto-commit-action-gh-pages
